package com.chernobyl.TicketWizard.model;

import java.time.LocalDateTime;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "tickets")
@Getter
@Setter
public class Ticket {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The public-facing proof-of-purchase identifier (e.g., encoded as a QR code).
    // Generated by PostgreSQL via DEFAULT gen_random_uuid() — NOT by Hibernate.
    // We do NOT use @GeneratedValue here; instead we tell JPA it is non-insertable
    // and non-updatable (the DB owns this value). Hibernate reads it back after INSERT.
    // UUID type is preferred over String: it makes the intent clear and avoids
    // accidentally passing arbitrary strings where a UUID is expected.
    @Column(name = "ticket_code", nullable = false, unique = true,
            insertable = false, updatable = false)
    private UUID ticketCode;

    // NULL = not yet scanned at the venue entrance.
    // A timestamp = the moment the ticket was validated (scanning is out of v1 scope,
    // but the column exists so no migration is needed when scanning is added).
    @Column(name = "scanned_at")
    private LocalDateTime scannedAt;

    // ── Relationships ───────────────────────────────────────────────────────────

    // Many tickets → one order (FK: tickets.order_id)
    // Ticket is the FK owner — it holds the order_id column.
    // No cascade upward: saving/deleting a Ticket should not cascade to its Order.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id")
    private Order order;

    // Many tickets → one ticket type (FK: tickets.ticket_type_id)
    // Records which tier (GENERAL, VIP, etc.) this ticket belongs to.
    // No cascade upward.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ticket_type_id")
    private TicketType ticketType;

    // ── Constructors ────────────────────────────────────────────────────────────

    public Ticket() {
    }

    public Ticket(Order order, TicketType ticketType) {
        this.order = order;
        this.ticketType = ticketType;
        // ticketCode is intentionally excluded — the DB generates it on INSERT.
        // It will be populated in the managed entity after Hibernate flushes.
    }
}
